In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
df=pd.get_dummies(df)
df.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False

In [7]:
df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [8]:
x=df[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest']]
y=df['charges']

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
r=[0.1,0.2,0.3,0.4,0.5]
MSE=[]
Random=[]
T=[]
for i in r:
    for j in range(1,51):
        x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=j,test_size=i)
        lr=LinearRegression()
        lr.fit(x_train,y_train)
        y_pred=lr.predict(x_test)
        M=mean_squared_error(y_test,y_pred)
        MSE.append(M)
        Random.append(j)
        T.append(i)

In [20]:
Data = {"random_state:":Random,"Test_size":T,"MSE":MSE}
df=pd.DataFrame(Data)
df

     random_state:  Test_size           MSE
0                1        0.1  4.310428e+07
1                2        0.1  3.390603e+07
2                3        0.1  3.953055e+07
3                4        0.1  3.989601e+07
4                5        0.1  3.123167e+07
..             ...        ...           ...
245             46        0.5  3.709951e+07
246             47        0.5  3.421207e+07
247             48        0.5  3.501140e+07
248             49        0.5  3.625376e+07
249             50        0.5  3.444655e+07

[250 rows x 3 columns]