In [29]:
import pandas as pd

In [30]:
df=pd.read_csv('Employee_Attrition.csv')
df.head()

,Employee_ID,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,1,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,2,56,31395,18,HR,Poor,Yes,1,7,School,1
2,3,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,4,39,20851,5,HR,Good,No,2,7,Graduate,0
4,5,28,32156,12,Developer,Good,No,3,26,School,0

In [31]:
df.isna().sum()

Employee_ID           0
Age                   0
Monthly_Income        0
Years_at_Company      0
Job_Role              0
Work_Life_Balance     0
Overtime              0
Job_Satisfaction      0
Distance_From_Home    0
Education             0
Attrition             0
dtype: int64

In [32]:
df.drop(columns="Employee_ID",inplace=True)

In [33]:
df=pd.get_dummies(data=df,drop_first=True)
df.head()

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
0,29,23278,8,1,22,1,False,False,True,False,True,True,True,False
1,56,31395,18,1,7,1,False,True,False,False,True,True,False,True
2,54,98907,0,2,15,0,False,False,True,False,False,False,True,False
3,39,20851,5,2,7,0,False,True,False,True,False,False,False,False
4,28,32156,12,3,26,0,True,False,False,True,False,False,False,True

In [34]:
x=df[['Age', 'Monthly_Income', 'Years_at_Company', 'Job_Satisfaction',
       'Distance_From_Home', 'Job_Role_Developer', 'Job_Role_HR',
       'Job_Role_Manager', 'Work_Life_Balance_Good', 'Work_Life_Balance_Poor',
       'Overtime_Yes', 'Education_Postgraduate', 'Education_School']]
y=df['Attrition']

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(x_test.shape)

(200, 13)
(50, 13)
(200,)
(50, 13)

In [44]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,recall_score
a = []
for i in range(1,26):
    nn=KNeighborsClassifier(n_neighbors=i)
    model=nn.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    accuracy =accuracy_score(y_test,y_pred)
    a.append(accuracy)
    print("accurecy : ",accuracy)

accurecy :  0.86
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94
accurecy :  0.94

In [49]:
print(a.index((max(a))))

1

# random forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=150,random_state=42,criterion='entropy',max_depth=12)