In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('PlayTennis.csv')
df.head()

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [7]:
df=pd.get_dummies(data=df,drop_first=True)
df.head()

,windy,outlook_rainy,outlook_sunny,temp_hot,temp_mild,humidity_normal,play_yes
0,False,False,True,True,False,False,False
1,True,False,True,True,False,False,False
2,False,False,False,True,False,False,True
3,False,True,False,False,True,False,True
4,False,True,False,False,False,True,True

In [9]:
df.columns

Index(['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal', 'play_yes'],
      dtype='object')

In [11]:
x=df[['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal']]
y=df["play_yes"]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(11, 6) (3, 6) (11,) (3,)

In [16]:
11**(0.5)

3.3166247903554

In [17]:
from sklearn.neighbors import KNeighborsClassifier
nn=KNeighborsClassifier(n_neighbors=3)

In [18]:
model=nn.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([ True, False,  True])

In [20]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test) 
cm

array([[0, 1],
       [1, 1]])

In [21]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]

In [23]:
print("Accuracy    : ", (TP+TN) / (TP+TN+FP+FN))
print("Error_rate  : ", (FP+FN) / (TP+TN+FP+FN))
print("Sensitivity : ", TP / (TP+FN))
print("Speciticity : ", TN / (TN+FP))

Accuracy    :  0.3333333333333333
Error_rate  :  0.6666666666666666
Sensitivity :  0.5
Speciticity :  0.0

In [26]:
df.columns

Index(['windy', 'outlook_rainy', 'outlook_sunny', 'temp_hot', 'temp_mild',
       'humidity_normal', 'play_yes'],
      dtype='object')

In [28]:
p=model.predict([[1,1,0,0,0,1]])
p

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([ True])