In [1]:
import pandas as pd

In [11]:
df=pd.read_csv("RealEstate.csv")
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [12]:
df.drop(columns="No",inplace=True)
df.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [16]:
df.isna().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [23]:
x=df[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']]
y=df['Y house price of unit area']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=110)
print(f"x_train : {x_train.shape}\nx_test : {x_test.shape}\ny_train : {y_train.shape}\ny_test : {y_test.shape}")

x_train : (289, 6)
x_test : (125, 6)
y_train : (289,)
y_test : (125,)

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [27]:
m=lr.coef_
m

array([ 6.84308941e+00, -2.25466590e-01, -5.18046265e-03,  1.12369103e+00,
        1.87739728e+02, -4.29300312e+01])

In [28]:
c=lr.intercept_
c

np.float64(-13203.674300629997)

In [ ]:
lr.predict([[]])

In [30]:
from sklearn.metrics import mean_squared_error
y_pred=lr.predict(x_test)
y_pred

array([40.06913335, 32.56470479, 29.80668902, 44.60809493, 39.96541473,
       44.34984726, 37.64834639, 51.18801909, 37.08044432, 38.64449437,
       36.45757424, 31.64776451, 43.03392987, 16.64984039, 36.61381207,
       31.21699197, 39.55333345, 41.89770923, 46.41953538, 42.69067202,
       40.49560609, 53.3447345 , 40.74436408, 36.67049204, 46.86499408,
       42.78349352, 47.25115307, 40.53653503, 42.57499139, 50.88772177,
       44.81813044, 41.05114011, 35.39386877, 42.95199941, 13.97578058,
       30.00463214,  0.32863779, 39.56884707, 47.9626967 , 34.0147913 ,
       40.23322474, 49.74492584, 36.73990519, 35.39784888, 29.6071314 ,
       45.83432319, 42.44745248, 37.88237609, 31.55675944, 47.517238  ,
       35.03089266, 45.17666152, 45.98711652, 47.32685806, 54.18178829,
       15.18888047, 43.78264851, 44.75385635, 37.69057227, 39.34215811,
       44.21812376, 44.27270068, 47.84570949, 38.42626454, 41.0626191 ,
       19.64522484, 47.9626967 , 43.85961508, 37.99756745, 43.80152052,
       42.39390912, 42.57768877, 44.73329588, 32.31758114, 46.89135756,
       38.92015239, 40.90438603, 43.95669962, 34.28075691, 25.5851042 ,
       16.26403643, 45.66098257, 42.05300968, 10.81561309, 31.65043887,
       49.10789869, 47.40016786, 13.5604683 , 46.02203009, 44.82145569,
       34.76747867, 35.40469328, 31.48202917, 45.59192922, 42.0246353 ,
       42.54274755, 14.70678074, 43.68554348, 27.69149444, 43.0460661 ,
       27.63908623, 35.23545719, 45.89665228, 50.31290226, 42.86214486,
       44.61671482, 49.59887911, 32.11577476, 31.86965512, 38.39003281,
       44.58865137, 25.50284004, 46.20113858, 37.45131001, 14.70678074,
       44.2357441 ,  9.25548578, 37.23816575, 38.97851394, 47.40016786,
       39.50115693, 32.15412829, 46.99435489, 47.07907957, 53.12308545])

In [33]:
print(mean_squared_error(y_pred,y_test))

77.14802598253598