In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("winequality.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [3]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [4]:
df.drop(columns='Id',inplace=True)

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [8]:
x=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]
y=df['quality']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(f"x_train : {x_train.shape}\nx_test : {x_test.shape}\ny_train : {y_train.shape}\ny_test : {y_test.shape}")

x_train : (914, 11)
x_test : (229, 11)
y_train : (914,)
y_test : (229,)

In [11]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [12]:
m=lr.coef_
m

array([ 5.13430654e-02, -1.33625691e+00, -3.39100758e-01,  4.12143173e-03,
       -1.80653035e+00,  1.88076181e-03, -2.28305818e-03, -3.06532562e+01,
       -2.49236344e-01,  9.73040097e-01,  2.66586068e-01])

In [14]:
c=lr.intercept_
c

np.float64(34.209805578378685)

In [15]:
y_pred=lr.predict(x_test)
y_pred

array([5.37639096, 4.81275231, 5.26822711, 5.08826518, 6.09668676,
       6.60433542, 5.36417303, 5.06978794, 5.78461148, 5.32382095,
       6.31298023, 6.39721516, 5.3122581 , 6.20451475, 5.86121236,
       4.84318641, 5.69306745, 5.70473751, 5.50099506, 6.4022271 ,
       6.06476494, 6.03726349, 5.17366124, 6.50195777, 5.60352313,
       5.10641179, 6.56067549, 5.96071079, 5.10316054, 5.57954028,
       6.20303322, 5.47600319, 6.59869683, 5.73347337, 5.55058293,
       5.26541133, 5.48831034, 6.05771316, 6.95448756, 6.57961946,
       6.4526993 , 5.34213598, 7.03445013, 5.37970557, 5.05503642,
       5.0554158 , 5.61860118, 5.8525548 , 4.63668652, 5.68553779,
       6.42194262, 5.26381661, 5.60884518, 5.88146705, 5.78923411,
       6.38843403, 5.50237456, 5.70598277, 6.0421496 , 5.23069794,
       5.52701136, 5.95270183, 5.60755482, 6.35884408, 6.15031671,
       5.38044967, 6.86150613, 5.26208169, 4.8615088 , 5.98738066,
       5.74523457, 5.33651712, 5.93642512, 5.94447105, 5.18598015,
       5.18018033, 5.88830754, 5.86364764, 5.59329182, 5.4312964 ,
       5.36245012, 5.5735966 , 6.05382462, 5.30356486, 5.53157336,
       6.00164733, 5.36913039, 5.69589453, 5.71149082, 5.29347895,
       4.63363761, 5.55965188, 5.02843281, 5.19656454, 5.01753272,
       5.17852805, 5.35541488, 6.62872452, 5.92027008, 5.55731116,
       5.73875188, 6.34663671, 5.20076847, 6.12385557, 5.19111773,
       5.34495603, 5.88110025, 6.15432075, 5.6174042 , 6.5520132 ,
       5.95326128, 5.31626038, 5.47807907, 6.04057588, 5.02769272,
       5.0856876 , 5.31312395, 6.39291934, 5.7776926 , 4.83051468,
       5.25014556, 4.92480222, 5.59042873, 6.6768142 , 5.15489521,
       5.72687946, 5.77508356, 5.77008009, 5.03945992, 6.35841554,
       5.15105191, 4.87189309, 5.92002605, 5.68751429, 7.52852916,
       4.67740394, 4.22000913, 5.50796393, 5.58744591, 5.75274095,
       6.95943297, 5.3293687 , 5.66769591, 4.90523117, 6.41996409,
       5.13866018, 5.11966503, 5.3845608 , 4.87609836, 4.94833329,
       6.58427849, 5.40129439, 6.3102733 , 5.33798589, 5.94770094,
       5.67820754, 5.3845608 , 5.82270224, 6.13585466, 5.72112693,
       5.91227255, 5.02937651, 5.74428233, 5.61301033, 5.71001112,
       5.37033651, 6.15443489, 6.03520859, 5.5903806 , 5.20731612,
       6.52109365, 5.3794929 , 5.44570186, 5.63116517, 5.3402766 ,
       5.19279249, 6.48136978, 6.03854629, 5.63301636, 5.39783076,
       6.10858474, 5.70143895, 5.58599878, 5.40703092, 5.190874  ,
       5.53445283, 6.29645821, 4.87008671, 6.34828052, 5.75105866,
       5.76634231, 5.79455429, 6.54822094, 5.7855001 , 5.56583393,
       5.46635649, 5.09555001, 6.54966905, 6.61063014, 6.28219938,
       5.72493264, 5.80848854, 5.28495763, 5.47745778, 5.91073221,
       5.50296246, 5.16694607, 5.23107818, 6.20462069, 6.20603035,
       5.07524448, 6.10916536, 5.51258542, 5.68139672, 5.48314648,
       5.11306556, 6.47966324, 5.03925381, 6.05723647, 5.78799703,
       5.63835362, 5.50317061, 5.02454776, 5.73725033, 4.76587288,
       6.11540211, 5.30551143, 5.46518581, 5.80330226])

In [16]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

0.38003245026277577

In [18]:
y=lr.predict([[8,0.4,0.40,.15,0.048,40,150,0.99,3,0.45,10.5]])
y

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.73967259])